version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "graphql-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-swrouu8gdbm5"
s3_prefix = "graphql-stack"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
